### ISSUE TITLE
can binary support centos7 ?

### ISSUE THREAD

**Issue by huanghuangzym** [imuxin/kubectl-watch#15]
can make binary build in glibc 2.17 to support centos7?

**Comment by huanghuangzym** [comment]
https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html

**Comment by imuxin** [comment]
I tried to compile in centos7 with gcc4.8 installed. But failed to build, got the error:
```
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-Wall" "-Wextra" "-ftls-model=initial-exec" "-DMI_DEBUG=0" "-o" "/root/ql/kubectl-watch/target/debug/build/libmimalloc-sys-83bf035ad26abe40/out/c_src/mimalloc/src/static.o" "-c" "c_src/mimalloc/src/static.c"
  cargo:warning=In file included from c_src/mimalloc/include/mimalloc-types.h:13:0,
  cargo:warning=                 from c_src/mimalloc/include/mimalloc-internal.h:11,
  cargo:warning=                 from c_src/mimalloc/src/static.c:17:
  cargo:warning=c_src/mimalloc/include/mimalloc-atomic.h:34:23: fatal error: stdatomic.h: No such file or directory
  cargo:warning= #include <stdatomic.h>
  cargo:warning=                       ^
  cargo:warning=compilation terminated.
  exit status: 1

  --- stderr
```

And I found glibc version must be greater than **4.9**.

> This file is missing. http://gcc.gnu.org/bugzilla/show_bug.cgi?id=58016
> It was fixed only in gcc 4.9, as its release notes says (http://gcc.gnu.org/gcc-4.9/changes.html)

References:

- https://github.com/cockroachdb/c-jemalloc/issues/8
- https://stackoverflow.com/questions/20326604/stdatomic-h-in-gcc-4-8

**Comment by huanghuangzym** [comment]
![image](https://github.com/imuxin/kubectl-watch/assets/15240576/12d6b948-cfd5-42ba-9d14-d78c83bbce99)
can use quay.io/pypa/manylinux2010_x86_64 to build ?
